-- ============================================================================
-- Flyway Migration V4: Add GENERATED BY DEFAULT AS IDENTITY to primary keys
-- ============================================================================
--
-- The original schema (V1) created primary key columns as plain SMALLINT
-- columns without any auto-increment mechanism. This caused INSERTs from
-- JPA (@GeneratedValue(strategy = IDENTITY)) to fail with "null value in
-- column violates not-null constraint" because Hibernate expected the DB to
-- generate the ID.
--
-- This migration adds GENERATED BY DEFAULT AS IDENTITY to all single-column
-- primary keys and advances each sequence past existing data.
-- ============================================================================

-- Add identity to all primary key columns
ALTER TABLE actor ALTER COLUMN actor_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE address ALTER COLUMN address_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE city ALTER COLUMN city_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE country ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE customer ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE film ALTER COLUMN film_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE inventory ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE language ALTER COLUMN language_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE rental ALTER COLUMN rental_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE staff ALTER COLUMN staff_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE store ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Advance each identity sequence past the highest existing value
SELECT setval(pg_get_serial_sequence('actor', 'actor_id'), COALESCE((SELECT MAX(actor_id) FROM actor), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('address', 'address_id'), COALESCE((SELECT MAX(address_id) FROM address), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('category', 'category_id'), COALESCE((SELECT MAX(category_id) FROM category), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('city', 'city_id'), COALESCE((SELECT MAX(city_id) FROM city), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('country', 'country_id'), COALESCE((SELECT MAX(country_id) FROM country), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('customer', 'customer_id'), COALESCE((SELECT MAX(customer_id) FROM customer), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('film', 'film_id'), COALESCE((SELECT MAX(film_id) FROM film), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('inventory', 'inventory_id'), COALESCE((SELECT MAX(inventory_id) FROM inventory), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('language', 'language_id'), COALESCE((SELECT MAX(language_id) FROM language), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('payment', 'payment_id'), COALESCE((SELECT MAX(payment_id) FROM payment), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('rental', 'rental_id'), COALESCE((SELECT MAX(rental_id) FROM rental), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('staff', 'staff_id'), COALESCE((SELECT MAX(staff_id) FROM staff), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('store', 'store_id'), COALESCE((SELECT MAX(store_id) FROM store), 0) + 1, false);

-- Grant privileges on the new identity sequences to the application user
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sakila_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO sakila_app;
