<#-- Hibernate Tools 6.x Compatible Template for Kotlin -->
<#-- Available objects: pojo, clazz -->
${pojo.getPackageDeclaration()}

import jakarta.persistence.*
import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalDateTime

<#-- Determine if this is a composite key class (Embeddable) -->
<#assign className = pojo.getDeclarationName()>
<#assign isCompositeKey = !pojo.hasIdentifierProperty() && className?ends_with("Id")>

<#-- For entities: check if they use a composite key -->
<#assign usesCompositeKey = false>
<#assign compositeKeyTypeName = "">
<#if !isCompositeKey>
<#list pojo.getAllPropertiesIterator() as property>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#if property.name == "id" && javaType?ends_with("Id")>
        <#assign usesCompositeKey = true>
        <#assign compositeKeyTypeName = javaType>
    </#if>
</#list>
</#if>

<#-- Helper function to convert Java types to Kotlin types -->
<#function toKotlinType javaType>
    <#if javaType == "int" || javaType == "Integer" || javaType == "java.lang.Integer">
        <#return "Int">
    <#elseif javaType == "long" || javaType == "Long" || javaType == "java.lang.Long">
        <#return "Long">
    <#elseif javaType == "short" || javaType == "Short" || javaType == "java.lang.Short">
        <#return "Short">
    <#elseif javaType == "byte" || javaType == "Byte" || javaType == "java.lang.Byte">
        <#return "Byte">
    <#elseif javaType == "double" || javaType == "Double" || javaType == "java.lang.Double">
        <#return "Double">
    <#elseif javaType == "float" || javaType == "Float" || javaType == "java.lang.Float">
        <#return "Float">
    <#elseif javaType == "boolean" || javaType == "Boolean" || javaType == "java.lang.Boolean">
        <#return "Boolean">
    <#elseif javaType == "char" || javaType == "Character" || javaType == "java.lang.Character">
        <#return "Char">
    <#elseif javaType == "String" || javaType == "java.lang.String">
        <#return "String">
    <#elseif javaType == "BigDecimal" || javaType == "java.math.BigDecimal">
        <#return "BigDecimal">
    <#elseif javaType == "LocalDate" || javaType == "java.time.LocalDate">
        <#return "LocalDate">
    <#elseif javaType == "LocalDateTime" || javaType == "java.time.LocalDateTime">
        <#return "LocalDateTime">
    <#elseif javaType == "byte[]" || javaType == "Byte[]">
        <#return "ByteArray">
    <#elseif javaType == "int[]" || javaType == "Integer[]">
        <#return "IntArray">
    <#elseif javaType == "long[]" || javaType == "Long[]">
        <#return "LongArray">
    <#elseif javaType == "short[]" || javaType == "Short[]">
        <#return "ShortArray">
    <#elseif javaType == "double[]" || javaType == "Double[]">
        <#return "DoubleArray">
    <#elseif javaType == "float[]" || javaType == "Float[]">
        <#return "FloatArray">
    <#elseif javaType == "boolean[]" || javaType == "Boolean[]">
        <#return "BooleanArray">
    <#elseif javaType == "char[]" || javaType == "Character[]">
        <#return "CharArray">
    <#elseif javaType?starts_with("Set<")>
        <#return "MutableSet<" + javaType?substring(4)>
    <#elseif javaType?starts_with("java.util.Set<")>
        <#return "MutableSet<" + javaType?substring(14)>
    <#else>
        <#return javaType>
    </#if>
</#function>

/**
 * ${className} generated by Hibernate Tools
 */
<#if isCompositeKey>
@Embeddable
data class ${className}(
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign kotlinType = toKotlinType(javaType)>
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
</#list>
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L
    }
}
<#else>
@Entity
@Table(name = "${clazz.table.name}"<#if clazz.table.schema?? && clazz.table.schema?has_content>, schema = "${clazz.table.schema}"</#if>)
class ${className}(
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign kotlinType = toKotlinType(javaType)>
    <#assign valueTypeName = property.value.class.simpleName>
    <#assign isId = pojo.hasIdentifierProperty() && pojo.getIdentifierProperty().name == propertyName>
    <#assign isEmbeddedId = propertyName == "id" && javaType?ends_with("Id")>

    <#if isEmbeddedId>
    @EmbeddedId
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif isId>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}")
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}")
    </#if>
    </#if>
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "ManyToOne">
    @ManyToOne(fetch = FetchType.LAZY)
    <#assign columnName = "">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    <#assign columnName = column.name>
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    <#assign columnName = column.name>
    </#if>
    </#if>
    <#if usesCompositeKey && columnName?has_content>
    <#assign mapsIdValue = columnName?lower_case?replace("_", " ")?capitalize?replace(" ", "")?uncap_first>
    @MapsId("${mapsIdValue}")
    </#if>
    <#if columnName?has_content>
    @JoinColumn(name = "${columnName}")
    </#if>
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "Set" || valueTypeName == "Bag" || valueTypeName == "List">
    <#assign mappedByValue = className?uncap_first>
    <#if propertyName?contains("For")>
        <#assign forIndex = propertyName?index_of("For")>
        <#if (forIndex > 0) && (forIndex < propertyName?length - 3)>
            <#assign columnSuffix = propertyName?substring(forIndex + 3)>
            <#assign mappedByValue = className?uncap_first + "By" + columnSuffix>
        </#if>
    </#if>
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "${mappedByValue}")
    var ${propertyName}: ${kotlinType} = mutableSetOf()<#if property_has_next>,</#if>
    <#elseif valueTypeName == "BasicValue" || valueTypeName == "SimpleValue">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if><#if (column.length)?? && column.length != 255 && (kotlinType == "String")>, length = ${column.length?c}</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "Component">
    @Embedded
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    <#else>
    // TODO: Unknown mapping type "${valueTypeName}" for property "${propertyName}"
    var ${propertyName}: ${kotlinType}? = null<#if property_has_next>,</#if>
    </#if>
</#list>
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L
    }
}
</#if>