<#-- Hibernate Tools 6.x Compatible Template -->
<#-- Available objects: pojo, clazz -->
${pojo.getPackageDeclaration()}

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

<#-- Determine if this is a composite key class (Embeddable) -->
<#assign className = pojo.getDeclarationName()>
<#assign isCompositeKey = !pojo.hasIdentifierProperty() && className?ends_with("Id")>

<#-- For entities: check if they use a composite key -->
<#assign usesCompositeKey = false>
<#assign compositeKeyTypeName = "">
<#assign compositeKeyFields = []>
<#if !isCompositeKey>
<#list pojo.getAllPropertiesIterator() as property>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#if property.name == "id" && javaType?ends_with("Id")>
        <#assign usesCompositeKey = true>
        <#assign compositeKeyTypeName = javaType>
    </#if>
</#list>
</#if>

/**
 * ${className} generated by Hibernate Tools
 */
<#if isCompositeKey>
@Embeddable
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class ${className} implements Serializable {
<#else>
@Entity
@Table(name = "${clazz.table.name}"<#if clazz.table.schema?? && clazz.table.schema?has_content>, schema = "${clazz.table.schema}"</#if>)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ${className} implements Serializable {
</#if>

    @Serial
    private static final long serialVersionUID = 1L;

<#-- Iterate over all properties -->
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign valueTypeName = property.value.class.simpleName>

    <#-- Check if this is the identifier -->
    <#assign isId = pojo.hasIdentifierProperty() && pojo.getIdentifierProperty().name == propertyName>

    <#-- Check if this is a composite/embedded id -->
    <#assign isEmbeddedId = propertyName == "id" && javaType?ends_with("Id")>

<#if isCompositeKey>
    <#-- For composite key classes, just generate columns without @Id -->
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    private ${javaType} ${propertyName};

<#else>
    <#-- Regular entity logic -->

    <#-- Handle EmbeddedId (composite primary key reference) -->
    <#if isEmbeddedId>
    @EmbeddedId
    private ${javaType} ${propertyName};

    <#-- Generate @Id annotation for simple primary key -->
    <#elseif isId>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}")
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}")
    </#if>
    </#if>
    private ${javaType} ${propertyName};

    <#-- Handle ManyToOne relationships -->
    <#elseif valueTypeName == "ManyToOne">
    @ManyToOne(fetch = FetchType.LAZY)
    <#-- Determine column name for potential @MapsId -->
    <#assign columnName = "">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    <#assign columnName = column.name>
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    <#assign columnName = column.name>
    </#if>
    </#if>
    <#-- If entity uses composite key, add @MapsId -->
    <#if usesCompositeKey && columnName?has_content>
    <#-- Convert ACTOR_ID -> actorId for @MapsId value -->
    <#assign mapsIdValue = columnName?lower_case?replace("_", " ")?capitalize?replace(" ", "")?uncap_first>
    @MapsId("${mapsIdValue}")
    </#if>
    <#if columnName?has_content>
    @JoinColumn(name = "${columnName}")
    </#if>
    private ${javaType} ${propertyName};

    <#-- Handle OneToMany relationships (Set, Bag, List) -->
    <#elseif valueTypeName == "Set" || valueTypeName == "Bag" || valueTypeName == "List">
    <#--
      Derive mappedBy value from property name pattern.
      Property naming pattern: {targetEntity}For{ColumnSuffix} (e.g., filmsForLanguageId)
      Inverse property pattern: {thisEntity}By{ColumnSuffix} (e.g., languageByLanguageId)
    -->
    <#assign mappedByValue = className?uncap_first>
    <#if propertyName?contains("For")>
        <#assign forIndex = propertyName?index_of("For")>
        <#if (forIndex > 0) && (forIndex < propertyName?length - 3)>
            <#assign columnSuffix = propertyName?substring(forIndex + 3)>
            <#assign mappedByValue = className?uncap_first + "By" + columnSuffix>
        </#if>
    </#if>
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "${mappedByValue}")
    @Builder.Default
    private ${javaType} ${propertyName} = new HashSet<>(0);

    <#-- Handle regular columns (BasicValue, SimpleValue, EnhancedBasicValue) -->
    <#elseif valueTypeName == "BasicValue" || valueTypeName == "SimpleValue" || valueTypeName == "EnhancedBasicValue">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if><#if (column.length)?? && column.length != 255 && javaType == "String">, length = ${column.length?c}</#if><#if javaType == "String">, columnDefinition = "VARCHAR"</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "${column.name}"<#if !column.nullable>, nullable = false</#if><#if javaType == "String">, columnDefinition = "VARCHAR"</#if>)
    </#if>
    </#if>
    private ${javaType} ${propertyName};

    <#-- Handle Component/Embedded types -->
    <#elseif valueTypeName == "Component">
    @Embedded
    private ${javaType} ${propertyName};

    <#-- Fallback for unknown types -->
    <#else>
    // TODO: Unknown mapping type "${valueTypeName}" for property "${propertyName}"
    private ${javaType} ${propertyName};

    </#if>
</#if>
</#list>
}